services:
  proxy:
    container_name: swkom-reverseproxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  frontend:
    container_name: swkom-presentation
    image: httpd:2.4
    depends_on:
      - proxy
    volumes:
      - ./src/static/:/usr/local/apache2/htdocs/
    command: sh -c "echo ServerName localhost >> /usr/local/apache2/conf/httpd.conf && httpd-foreground"
  api:
    container_name: swkom-api
    image: swkom-api
    depends_on:
      - proxy
    build: .
    restart: always