version: '3.4'

services:
  database:
    container_name: swkom-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: swkom-db
      POSTGRES_USER: swkom-db
      POSTGRES_PASSWORD: swkom-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    image: swkom-api
    container_name: swkom-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8081:8081

volumes:
  db-data: