version: '3.4'

services:
  api:
    image: paperless-api
    container_name: paperless-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8081:8081
    volumes:
      - ./NPaperless.API:/app
      - /app/bin
      - /app/obj
