services:
  proxy:
    container_name: swkom-reverseproxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  frontend:
    container_name: swkom-presentation
    image: httpd:2.4
    depends_on:
      - proxy
    ports:
    - 8000:80
    volumes:
      - ./src/static/:/usr/local/apache2/htdocs/
    command: echo "ServerName localhost" >> /etc/apache2/apache2.conf
  api:
    container_name: swkom-api
    image: swkom-api
    depends_on:
      - proxy
    ports:
      - 8001:80
    build: .
    restart: always